spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb+srv://ajaydv1263:Sairam%401970@cluster-fitness.zuwxuda.mongodb.net/fitnessactivity?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000&maxPoolSize=50



  rabbitmq:
    addresses: amqps://revieqfp:nTSpY6ZpxTjqR1xloDPmQ02DtxOcpKXi@campbell.lmq.cloudamqp.com/revieqfp
    virtual-host: revieqfp

server:
  port: 8082



rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://spring-eureka-microservice.onrender.com/eureka/
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 90




