server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb+srv://ajaydv1263:Sairam%401970@cluster-fitness.zuwxuda.mongodb.net/fitnessrecommendation?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000&maxPoolSize=50

  rabbitmq:
    addresses: campbell.lmq.cloudamqp.com
    username: revieqfp
    password: nTSpY6ZpxTjqR1xloDPmQ02DtxOcpKXi
    virtual-host: revieqfp
    ssl: true
    exchange:
      name: fitness.exchange
    queue:
      name: activity.queue
    routing:
      key: activity.tracking
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000
          multiplier: 1.5
          max-interval: 10000

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://spring-eureka-microservice.onrender.com/eureka/
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
