server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db.tuklojaztngcyekusisd.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: fitnessuserdb2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


