name: Auto Redeploy to Render

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4g011fgi27c73b5jtk0?key=WZJ0ovtNDdw
